---
# See https://github.com/jesseduffield/lazygit/blob/master/pkg/config/user_config.go for the yaml keys
gui:
  expandFocusedSidePanel: true
  mouseEvents: false
  showIcons: true
keybinding:
  universal:
    prevPage: "<C-b>"
    nextPage: "<C-f>"
    # Alt key is not supported
    # scrollUpMain-alt1: "<A-k>"
    # scrollDownMain-alt1: "<A-j>"
  files:
    openStatusFilter: "."
os:
  # See: https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#custom-command-for-copying-to-and-pasting-from-clipboard
  # Command for tmux is modified as the original one hangs a bit after copying
  copyToClipboardCmd: >
    if string match --regex '^tmux' "$TERM"
        tmux set-buffer "{{text}}"
    else
        printf "\033]52;c;$(echo {{text}} | base64 | string trim)\a" > /dev/tty
    end
